(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
(0:0) when the script is started,
    (5:250) create a table as %myTable.
    (5:100) set %hello to {hi}
    (5:101) set %i to 0
    (5:252) with table %myTable put {%hello} in it at key {myKey1}.
    (5:252) with table %myTable put {%hello} in it at key {myKey2}.
    (5:252) with table %myTable put {%hello} in it at key {myKey3}.
    (5:252) with table %myTable put {%hello} in it at key {myKey4}.
    (5:252) with table %myTable put {%hello} in it at key {myKey5}.
    (5:252) with table %myTable put {%hello} in it at key {myKey6}.
    (5:252) with table %myTable put {%hello} in it at key {myKey7}.
    (5:252) with table %myTable put {123} in it at key {123}.
    (6:250) for each entry in table %myTable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%i} to the console.
    (0:450) after the loop is done,
        (5:150) take variable %myTable[123] and add 1 to it.
        (5:102) print {%myTable[123]} to the console.

(0:0) when the script is started,
    (5:101) set %answer to 0
    (5:101) set %life to 42
    (6:450) while variable %answer is not %life,
        (5:150) take variable %answer and add 1 to it.
        (1:102) and variable %answer equals 21,
            (5:450) exit the current loop.
    (0:450) after the loop is done,
        (5:102) print {We may never know the answer...} to the console.

(0:0) when the script is started,
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.
        (5:102) print {%i} to the console.

(0:0) when the script is started,
    (5:250) create a table as %mytable
    (5:251) with table %mytable put 123 in it at key {123}.
    (6:250) for each entry in table %mytable put it into %entry,
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
        (5:102) print {%entry} to the console.
    (0:450) after the loop is done,
        (5:102) print {%mytable[123]} to the console.
